services:
  web:
    build: ./frontend
    image: toyrce:frontend
    ports:
      - "5173:3000"
  api:
    build: ./api
    image: toyrce:api
    env_file:
      - ./api/.env
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quandry
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
