version: "3.8"

services:
  javascript:
    build:
      context: ./environments/javascript
      dockerfile: Dockerfile
    image: toyrce:javascript
  python:
    build:
      context: "./environments/python"
      dockerfile: Dockerfile
    image: toyrce:python
  java:
    build: ./environments/java
    image: toyrce:java
